//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todd.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class AspNetUser 
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Calendars = new HashSet<Calendar>();
            this.CalendarUsersInRoles = new HashSet<CalendarUsersInRole>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIPCode { get; set; }
        public string CellPhone { get; set; }
        public string OtherPhone { get; set; }
        public Nullable<bool> IncludeInDirectory { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> FirstLogin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual ICollection<CalendarUsersInRole> CalendarUsersInRoles { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }

        
    }
}
