//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todd.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarType
    {
        public CalendarType()
        {
            this.Calendars = new HashSet<Calendar>();
        }
    
        public int CalendarTypeId { get; set; }
        public string CalendarTypeName { get; set; }
        public string CalendarTypeDescription { get; set; }
    
        public virtual ICollection<Calendar> Calendars { get; set; }
    }
}
