//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todd.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using Todd.ObjectInterfaces;

    public partial class CalendarEventDate : Entity
    {
        public int EventDateId { get; set; }
        public Nullable<int> CalendarEventId { get; set; }
        public Nullable<bool> Repeats { get; set; }
        public Nullable<int> RepeatTypeId { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public string RepeatsOn { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> StopOccurrences { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
    
        public virtual CalendarEvent CalendarEvent { get; set; }
        public virtual RepeatType RepeatType { get; set; }

        [NotMapped]
        public State State { get; set; }
        [NotMapped]
        public int _Id;
        public int Id
        {
            get { return _Id; }
            set { this._Id = EventDateId; }
        }
    }
}
