//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todd.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using Todd.ObjectInterfaces;
    
    public partial class RepeatType : Entity 
    {
        public RepeatType()
        {
            this.CalendarEventDates = new HashSet<CalendarEventDate>();
        }
    
        public int RepeatTypeId { get; set; }
        public string RepeatTypeName { get; set; }
        public string RepeatTypeDescription { get; set; }
    
        public virtual ICollection<CalendarEventDate> CalendarEventDates { get; set; }

        [NotMapped]
        public State State { get; set; }
        [NotMapped]
        public int _Id;
        public int Id
        {
            get { return _Id; }
            set { this._Id = RepeatTypeId; }
        }
    }
}
